### ISSUE TITLE
Different version of periodic table

### ISSUE THREAD

**Issue by Tony-Feng** [tamalweb/periodic-table#33]
Hi Tamal,

Thanks for sharing the implementation of this nice periodic table! I noticed that in your repo, the master and production branches show the same periodic table as this site: https://periodictable.website/. However, there is a different table on your GitHub page: https://tamalweb.github.io/periodic-table/. I didn't find the implementation for the GitHub page, just curious, would you share your implementation used for GitHub page as well?

Thanks in advance.

**Comment by tamalweb** [comment]
Hey Tony, that must be from an old version. You can use this info to deploy a React project using Github pages https://www.freecodecamp.org/news/deploy-a-react-app-to-github-pages/

**Comment by Tony-Feng** [comment]
Hello Tamal,

Yeah, it's an old version, and I found it here: 9d9ead7db7. Thanks a lot for your implementation and the deployment info!
